1|pub const NOISE_DIRS: &[&str] = &[
2|    "node_modules",
3|    ".git",
4|    "target",
5|    "__pycache__",
6|    ".next",
7|    "dist",
8|    "build",
9|    ".cache",
10|    ".turbo",
11|    ".vercel",
12|    ".pytest_cache",
13|    ".mypy_cache",
14|    ".tox",
15|    ".venv",
16|    "venv",
17|18|    "env", // Python legacy virtualenv dir — noise. .env (dotenv) is intentionally NOT here: agents must see it.
19|21|    "coverage",
22|    ".nyc_output",
23|    ".DS_Store",
24|    "Thumbs.db",
25|    ".idea",
26|    ".vscode",
27|    ".vs",
28|    "*.egg-info",
29|    ".eggs",
30|];
31|